repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        exclude: ^modules/grpc

  - repo: http://github.com/jazzband/pip-tools
    rev: 6.12.0
    hooks:
      - id: pip-compile

  - repo: http://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: ^modules/grpc


  - repo: http://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: modules/grpc
        additional_dependencies:
          - flake8-bugbear
          - flake8-print

#  - repo: http://github.com/pre-commit/mirrors-mypy
#    rev: v0.991
#    hooks:
#      - id: mypy
#        exclude: ^modules/grpc

  - repo: http://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.189
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^modules/grpc

#  - repo: http://github.com/pycqa/isort
#    rev: 5.11.2
#    hooks:
#      - id: isort

