repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade

  - repo: http://github.com/jazzband/pip-tools
    rev: 6.12.0
    hooks:
      - id: pip-compile
        files: requirements.in

  - repo: http://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: \.(py)$
        additional_dependencies:
          - flake8-bugbear
          - flake8-print

  - repo: http://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: \.(py)$

#  - repo: http://github.com/pycqa/isort
#    rev: 5.11.2
#    hooks:
#      - id: isort

  - repo: http://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: \.(py)$

  - repo: http://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.189
    hooks:
      - id: ruff
        files: \.(py)$