"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from abc import (
    ABCMeta,
    abstractmethod,
)
from apis.dm_api_search.search_pb2 import (
    SearchRequest,
    SearchResponse,
)
from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryUnaryMultiCallable,
)

class SearchEngineStub:
    def __init__(self, channel: Channel) -> None: ...
    Search: UnaryUnaryMultiCallable[
        SearchRequest,
        SearchResponse,
    ]

class SearchEngineServicer(metaclass=ABCMeta):
    @abstractmethod
    def Search(
        self,
        request: SearchRequest,
        context: ServicerContext,
    ) -> SearchResponse: ...

def add_SearchEngineServicer_to_server(servicer: SearchEngineServicer, server: Server) -> None: ...
